# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = E:\Develop\CLion\bin\cmake\win\bin\cmake.exe

# The command to remove a file.
RM = E:\Develop\CLion\bin\cmake\win\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = G:\project\cpp_learn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = G:\project\cpp_learn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	E:\Develop\CLion\bin\cmake\win\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache

.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	E:\Develop\CLion\bin\cmake\win\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache

.PHONY : rebuild_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start G:\project\cpp_learn\CMakeFiles G:\project\cpp_learn\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start G:\project\cpp_learn\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean

.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cpp_learn

# Build rule for target.
cpp_learn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) cpp_learn
.PHONY : cpp_learn

# fast build rule for target.
cpp_learn\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\cpp_learn.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cpp_learn.dir\build
.PHONY : cpp_learn\fast

main.obj: main.c.obj

.PHONY : main.obj

# target to build an object file
main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\cpp_learn.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cpp_learn.dir\main.c.obj
.PHONY : main.c.obj

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\cpp_learn.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cpp_learn.dir\main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\cpp_learn.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cpp_learn.dir\main.c.s
.PHONY : main.c.s

src\calculate.obj: src\calculate.c.obj

.PHONY : src\calculate.obj

# target to build an object file
src\calculate.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\cpp_learn.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cpp_learn.dir\src\calculate.c.obj
.PHONY : src\calculate.c.obj

src\calculate.i: src\calculate.c.i

.PHONY : src\calculate.i

# target to preprocess a source file
src\calculate.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\cpp_learn.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cpp_learn.dir\src\calculate.c.i
.PHONY : src\calculate.c.i

src\calculate.s: src\calculate.c.s

.PHONY : src\calculate.s

# target to generate assembly for a file
src\calculate.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\cpp_learn.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cpp_learn.dir\src\calculate.c.s
.PHONY : src\calculate.c.s

src\translation.obj: src\translation.c.obj

.PHONY : src\translation.obj

# target to build an object file
src\translation.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\cpp_learn.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cpp_learn.dir\src\translation.c.obj
.PHONY : src\translation.c.obj

src\translation.i: src\translation.c.i

.PHONY : src\translation.i

# target to preprocess a source file
src\translation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\cpp_learn.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cpp_learn.dir\src\translation.c.i
.PHONY : src\translation.c.i

src\translation.s: src\translation.c.s

.PHONY : src\translation.s

# target to generate assembly for a file
src\translation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\cpp_learn.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cpp_learn.dir\src\translation.c.s
.PHONY : src\translation.c.s

src\utility.obj: src\utility.c.obj

.PHONY : src\utility.obj

# target to build an object file
src\utility.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\cpp_learn.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cpp_learn.dir\src\utility.c.obj
.PHONY : src\utility.c.obj

src\utility.i: src\utility.c.i

.PHONY : src\utility.i

# target to preprocess a source file
src\utility.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\cpp_learn.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cpp_learn.dir\src\utility.c.i
.PHONY : src\utility.c.i

src\utility.s: src\utility.c.s

.PHONY : src\utility.s

# target to generate assembly for a file
src\utility.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\cpp_learn.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cpp_learn.dir\src\utility.c.s
.PHONY : src\utility.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... cpp_learn
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... src/calculate.obj
	@echo ... src/calculate.i
	@echo ... src/calculate.s
	@echo ... src/translation.obj
	@echo ... src/translation.i
	@echo ... src/translation.s
	@echo ... src/utility.obj
	@echo ... src/utility.i
	@echo ... src/utility.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

